### ISSUE TITLE
Penpot not working on my instance

### ISSUE THREAD

**Issue by Jioleoo** [YunoHost-Apps/penpot_ynh#34]
### Describe the bug

When I go on penpot and it shows "Bad Gateway Il semble que vous deviez attendre un peu et réessayer ; nous effectuons une petite maintenance de nos serveurs."

So i did look on the log and found this error:

`org.postgresql.util.PSQLException: ERROR: permission denied to create extension "uuid-ossp" Hint: Must be superuser to create this extension.`

### Context

After installing Penpot on my instance (vps), had to go check the log in ssh, on webadmin I only got the stacktrace.

**Comment by orhtej2** [comment]
Should be resolved once the catalog roll (or manually by upgrading from `testing` branch)
